tx = input('Digite algo: ')
print('O que foi digitado é: ',tx)
print('O tipo primitivo desse valor é', type(tx))
print('Só tem espaço? ',tx.isspace())
print('É um numero? ',tx.isnumeric())
print('É alfabetico? ',tx.isalpha())
print('É alfanumerica? ',tx.isalnum())
print('Está em maiusculas? ',tx.isupper())
print('Está em minusculas? ',tx.islower())
print('Está capitalizada? ',tx.istitle())